In [32]:
import pandas as pd
import numpy as np

In [21]:
data = pd.read_csv("leakage.csv", sep=",")

In [38]:
np.where(data[["p653"]].values > 0)

(array([17960, 17961, 17962, ..., 35856, 35857, 35858]),
 array([0, 0, 0, ..., 0, 0, 0]))

In [42]:
data.iloc[17960]

Timestamp    08:40:00
p123              0.0
p142              0.0
p193              0.0
p257              6.8
p277              0.0
p280             5.23
p331              0.0
p426              0.0
p427             5.05
p455              0.0
p514              0.0
p523              0.0
p586              0.0
p653             0.01
p654             5.44
p680              0.0
p710              0.0
p721              0.0
p762              0.0
p800              0.0
p810             6.85
p827              0.0
p879              0.0
Name: 2019-03-04, dtype: object

In [39]:
data[["p653"]].iloc[17960]

p653    0.01
Name: 2019-03-04, dtype: float64

In [20]:
f = lambda x: x if x is not str or x.count(":") >= 0 else "a"#float(x.replace(",","."))
data.applymap(f)

,Timestamp,p123,p142,p193,p257,p277,p280,p331,p426,p427,...,p653,p654,p680,p710,p721,p762,p800,p810,p827,p879
0,2019-01-01 00:00:00,0,0,0,"6,79",0,0,0,0,"5,05",...,0,"5,45",0,0,0,0,0,"6,87",0,0
1,2019-01-01 00:05:00,0,0,0,"6,8",0,0,0,0,"5,06",...,0,"5,45",0,0,0,0,0,"6,87",0,0
2,2019-01-01 00:10:00,0,0,0,"6,8",0,0,0,0,"5,06",...,0,"5,45",0,0,0,0,0,"6,87",0,0
3,2019-01-01 00:15:00,0,0,0,"6,8",0,0,0,0,"5,06",...,0,"5,45",0,0,0,0,0,"6,87",0,0
4,2019-01-01 00:20:00,0,0,0,"6,8",0,0,0,0,"5,05",...,0,"5,45",0,0,0,0,0,"6,87",0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105115,2019-12-31 23:35:00,"9,04",0,"10,19","6,76","7,28","5,21","10,52","13,22","4,96",...,0,"5,39","5,37","5,45","12,93","15,51",0,"6,78",0,"10,91"
105116,2019-12-31 23:40:00,"9,03",0,"10,19","6,76","7,28","5,21","10,51","13,21","4,96",...,0,"5,39","5,36","5,44","12,93","15,5",0,"6,77",0,"10,91"
105117,2019-12-31 23:45:00,"9,04",0,"10,2","6,76","7,28","5,21","10,53","13,23","4,96",...,0,"5,39","5,37","5,45","12,94","15,52",0,"6,78",0,"10,92"
105118,2019-12-31 23:50:00,"9,03",0,"10,19","6,76","7,28","5,21","10,52","13,22","4,96",...,0,"5,39","5,36","5,44","12,92","15,5",0,"6,77",0,"10,92"
105119,2019-12-31 23:55:00,"9,05",0,"10,21","6,77","7,29","5,22","10,55","13,25","4,97",...,0,"5,4","5,36","5,46","12,95","15,53",0,"6,79",0,"10,93"

In [11]:
"6,79".replace(",",".")

6.79